data:
  events_dir: "data/event_camera/split_events"
  num_bins: 5
  width: 240
  height: 180
  if_normalize: True
  flip: False
unet:
  in_channels: 5
  out_channels: 1
  skip_type: "no_skip"
  activation: "relu"
  base_channels: 16
  num_res_blocks: 2
  norm:
  rnn_type: "ConvGRU"
  rnn_blocks:
    resblock: [0]
train:
  cuda: True
  epochs: 75
  batch_size: 2
  lr: 0.0005
test:
  cuda: True
  checkpoint: "work_dir/fire_net/epoch_17.pth"
work_dir: "work_dir/fire_net"
