data:
  events_dir: "data/event_camera/split_events"
  num_bins: 5
  width: 240
  height: 180
  if_normalize: True
  flip: False
unet:
  in_channels: 5
  out_channels: 1
  skip_type: "sum"
  activation: "sigmoid"
  num_encoders: 4
  base_channels: 32
  num_res_block: 2
  norm:
  use_upsample_conv: True
  rnn_type: "ConvGRU"
train:
  cuda: True
  epochs: 50
  batch_size: 1